debug:
	g++ -g ./SQL/SqlCon.cpp ./Communi_Core.cpp ./Server_Main.cpp -o Server_Main.out -pthread -lmysqlclient

client:
	g++ -g ./SQL/SqlCon.cpp ./Communi_Core.cpp ./Client_demo.cpp  -pthread -lmysqlclient Client_demo.out
